project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "!slides/**/[0-9]*.qmd"

website:
  page-navigation: true
  title: "AI-Powered Clinical Reporting in R with the Pharmaverse"
  description: "posit::conf(2026) Workshop"
  favicon: "images/pharmaverse-hex.png"

  repo-url: https://github.com/posit-conf-2026/pharmaverse
  repo-actions: [edit, issue]

  page-footer:
    left: "This page is built with ❤️ and [Quarto](https://quarto.org/). Inspired by [@minecr.bsky.social](https://bsky.app/profile/minecr.bsky.social)."
    background: "#F3F7FB"

  sidebar:
    background: "#F3F7FB"
    logo: "images/pharmaverse-hex.png"
    pinned: true
    align: center
    tools:
      - icon: github
        href: https://github.com/posit-conf-2026/pharmaverse
        text: GitHub
    style: docked
    contents:
     - href: index.qmd
       text: Home
     - href: communications.qmd
       text: Communications
     - href: exercises/exercises.qmd
     - href: license.qmd

format:
  html:
    theme: [cosmo, theme.scss]
    toc: true
    code-copy: true
    code-overflow: scroll
    mainfont: "Atkinson Hyperlegible"
    highlight-style: a11y
    title-block-banner: "#003559"
    title-block-banner-color: white

editor: source

