---
title: "Exercises + Solutions"
editor: source
---

# Exercises

## `02-SDTM.R`

```{r}
#| echo: false
#| class-output: "sourceCode r"

"02-SDTM.R" |> 
  readLines() |> 
  cat(sep = "\n")
```

## `03-ADaM.R`

```{r}
#| echo: false
#| class-output: "sourceCode r"

"03-ADaM.R" |> 
  readLines() |> 
  cat(sep = "\n")
```

## `04-ARD.R`

```{r}
#| echo: false
#| class-output: "sourceCode r"

"04-ARD.R" |> 
  readLines() |> 
  cat(sep = "\n")
```

## `05-tables-gtsummary.R`

```{r}
#| echo: false
#| class-output: "sourceCode r"

"05-tables-gtsummary.R" |>
  readLines() |>
  cat(sep = "\n")
```

## `06-tables-tfrmt.R`

```{r}
#| echo: false
#| class-output: "sourceCode r"

"06-tables-tfrmt.R" |>
  readLines() |>
  cat(sep = "\n")
```


# Solutions

## `02-SDTM.R`

```{r}
#| echo: false
#| class-output: "sourceCode r"

"answers/02-SDTM-answer.R" |> 
  readLines() |> 
  cat(sep = "\n")
```

## `03-ADaM.R`

```{r}
#| echo: false
#| class-output: "sourceCode r"

"answers/03-ADaM-answer.R" |> 
  readLines() |> 
  cat(sep = "\n")
```

## `04-ARD.R`

```{r}
#| echo: false
#| class-output: "sourceCode r"

"answers/04-ARD-answer.R" |> 
  readLines() |> 
  cat(sep = "\n")
```

## `05-tables-gtsummary.R`

```{r}
#| echo: false
#| class-output: "sourceCode r"

"answers/05-tables-gtsummary-answer.R" |>
  readLines() |>
  cat(sep = "\n")
```

## `06-tables-tfrmt.R`

```{r}
#| echo: false
#| class-output: "sourceCode r"

"answers/06-tables-tfrmt-answer.R" |>
  readLines() |>
  cat(sep = "\n")
```
