---
title: Model Context Protocol
subtitle: Programming with LLMs in R and Python
author: <code>posit::conf(2026)</code>
date: 2026-09-14

editor:
  render-on-save: true
---

# [MCP]{.hidden} {.no-invert-dark-mode .center background-image="assets/robot-mcp.jpg" background-size="cover" background-position="center"}

::: {.tc .white .pa1 .br3 .w-50 .absolute bottom="-2em" left=0 style="font-size: 3em; background-color: rgba(0, 0, 0, 0.8);"}
MCP
:::

## Recall: Tools {.center}

a.k.a. _functions_, _tool calling_ or _function calling_

* Bring real-time or up-to-date information to the model

* Let the model interact with the world

## 🤔 What other tools could be useful?

```{=html}
<ul contenteditable="true">
<li>Get the weather</li>
<li>Search the <code>posit::conf()</code> schedule</li>
<li>...</li>
</ul>
```

::: notes
Some ideas:

* web search
* search a ticket system (zendesk)
* search a website or knowledge base
* Create tickets
* Send emails
* Read your calendar
* Summarize your email
:::

## 🤔 What GitHub-related tools would be useful?

```{=html}
<ul contenteditable="true">
<li>List issues</li>
<li>...</li>
</ul>
```

::: notes
Some ideas:

* web search
* search a ticket system (zendesk)
* search a website or knowledge base
* Create tickets
* Send emails
* Read your calendar
* Summarize your email
:::

## Who should write tools for GitHub? {.center}

::: fragment
MCP solves this problem! GitHub writes tools...
:::

::: fragment
and lets ~~you~~ your models use them.

[GitHub MCP Server](https://github.com/github/github-mcp-server#tools){preview-link=true}
:::

<!-- TODO: Adding MCP tools to ellmer, chatlas -->

# Your Turn `52_mcp` {.slide-your-turn}

Follow the instructions in `README.R.md` or `README.py.md` for this task.

1. What MCP servers are out there?

1. Set up [context7](https://context7.com/) as an MCP server in Positron.

1. Use [context7](https://context7.com/) tools to answer a coding translation question.

{{< countdown 6:00 left=0 bottom="-1.5em" >}}
